### ISSUE TITLE
access restrictions

### ISSUE THREAD

**Issue by zhuyifei1999** [Toollabs/video2commons#50] opened 2016-06-16 17:18 UTC
Alternative to #13 

Eg. Require # of edits before using this tool? Require autoconfirmed?

**Comment by Gunnex** [comment] 2016-06-16 17:59
Background: 
- [Commons and testwiki used as video hoster by Wikipedia Zero](https://phabricator.wikimedia.org/T129845)
- [User:NahidSultan/Bangladesh Facebook Case](https://commons.wikimedia.org/wiki/User:NahidSultan/Bangladesh_Facebook_Case)

and: [266 socks till 16.04.2016](https://commons.wikimedia.org/w/index.php?title=User:NahidSultan/Bangladesh_Facebook_Case/Accounts&oldid=193410089) --> now — 2 months later — [676 socks](https://commons.wikimedia.org/wiki/User:NahidSultan/Bangladesh_Facebook_Case/Accounts)... with daily uploads from copyrighted video sources --> [see filter "OAuth CID: 394"](https://commons.wikimedia.org/w/index.php?title=Special:RecentChanges&days=30&from=&limit=1000&tagfilter=OAuth+CID%3A+394) --> most of the "red links" are related = +300 deleted uploads since 17.05.2016 = 1 month.

The idea is to restrict access to video2commons only for a certain user group, based on status (auto-confirmed) or on (living) user edits (> 20, 50, 100, X) as all uploads are coming from fresh registered users (rarely: or from 0-edit sleepers). 

Maybe introduce the access restriction only for a certain period (1-3 month). Don't know if this restriction would also affect "good" but fresh users but — so far as I can evalute this — most of the "good" (and living) videos were uploaded by users with a greater experience and amount of edits in Commons... so I personally would prefer a solution with +50 or +100 edits...

**Comment by zhuyifei1999** [comment] 2016-06-17 00:21
@Steinsplitter @wilfredor @owcz any comments? If not I'll go with 50 edits.

**Comment by zhuyifei1999** [comment] 2016-06-17 00:22
Also @NahidSultan

**Comment by owcz** [comment] 2016-06-17 03:34
Eh, this would be a good case for a "verified uploader" user permission level...

50 edits seems like a reasonable place to start. The tradeoff is that abusers might rack up 50 junk edits somewhere to meet the quota. [Autoconfirmed](https://commons.wikimedia.org/wiki/Commons:User_access_levels#Autoconfirmed_users) + 50 edits could be a good idea. I don't think it would be a big deal to ratchet up the requirements if there are more bad actors, but that's the balance between openness and security.

**Comment by zhuyifei1999** [comment] 2016-06-17 07:23
@NahidSultan are sleepers common per your CU results? do you think 4 day wait requirement worth it?

**Comment by NahidSultan** [comment] 2016-06-17 08:28
Autoconfirmed + 50 edits sounds very much reasonable to me. Thanks Gunnex for initiating this thread. I usually use loginwiki cu interface for checking and yes, there are hundreds of them. As my understanding from this, they now know that we monitor commons account creation so they use other wikis (meta, enwiki etc) to create accounts and than wait few days. Usually, they create more than one account and switch to another one immediately after got blocked. I even locked many of them because they are not merged with commons yet (see the example of Razudelwar (https://login.wikimedia.org/w/index.php?title=Special%3AListUsers&username=Razudelwar&group=&limit=50) for instance).  Also as per Gunnex said above, most of the valid uploads via v2c are from experienced users so I think it's a good idea.

**Closed** 2016-06-17 12:02 UTC
Labels: frontend-general
